branch-defaults:
  master:
    environment: horseback-dev
    group_suffix: null
global:
  application_name: horse_backend
  default_ec2_keyname: dannyng-aws
  default_platform: Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git
